#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE09FEF25D96484AC (mcepl@suse.cz)
#
Name     : M2Crypto
Version  : 0.33.0
Release  : 7
URL      : https://files.pythonhosted.org/packages/52/e3/85f7ad64cd50b4c361b6533baeaa4d3919087993f24a93b34ae841a42628/M2Crypto-0.33.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/52/e3/85f7ad64cd50b4c361b6533baeaa4d3919087993f24a93b34ae841a42628/M2Crypto-0.33.0.tar.gz
Source99 : https://files.pythonhosted.org/packages/52/e3/85f7ad64cd50b4c361b6533baeaa4d3919087993f24a93b34ae841a42628/M2Crypto-0.33.0.tar.gz.asc
Summary  : M2Crypto: A Python crypto and SSL toolkit
Group    : Development/Tools
License  : MIT MIT-Opengroup
Requires: M2Crypto-license = %{version}-%{release}
Requires: M2Crypto-python = %{version}-%{release}
Requires: M2Crypto-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : openssl-dev
Patch1: build.patch
Patch2: rc4.patch

%description
This directory contains contributions by users of M2Crypto. Some of these
may get folded into the main distribution in time.

%package license
Summary: license components for the M2Crypto package.
Group: Default

%description license
license components for the M2Crypto package.


%package python
Summary: python components for the M2Crypto package.
Group: Default
Requires: M2Crypto-python3 = %{version}-%{release}
Provides: m2crypto-python

%description python
python components for the M2Crypto package.


%package python3
Summary: python3 components for the M2Crypto package.
Group: Default
Requires: python3-core

%description python3
python3 components for the M2Crypto package.


%prep
%setup -q -n M2Crypto-0.33.0
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557075964
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/M2Crypto
cp LICENCE %{buildroot}/usr/share/package-licenses/M2Crypto/LICENCE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/M2Crypto/LICENCE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
