#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE09FEF25D96484AC (mcepl@suse.cz)
#
Name     : M2Crypto
Version  : 0.35.2
Release  : 8
URL      : https://files.pythonhosted.org/packages/74/18/3beedd4ac48b52d1a4d12f2a8c5cf0ae342ce974859fba838cbbc1580249/M2Crypto-0.35.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/74/18/3beedd4ac48b52d1a4d12f2a8c5cf0ae342ce974859fba838cbbc1580249/M2Crypto-0.35.2.tar.gz
Source1  : https://files.pythonhosted.org/packages/74/18/3beedd4ac48b52d1a4d12f2a8c5cf0ae342ce974859fba838cbbc1580249/M2Crypto-0.35.2.tar.gz.asc
Summary  : M2Crypto: A Python crypto and SSL toolkit
Group    : Development/Tools
License  : MIT MIT-Opengroup
Requires: M2Crypto-license = %{version}-%{release}
Requires: M2Crypto-python = %{version}-%{release}
Requires: M2Crypto-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : openssl-dev
BuildRequires : python3-dev
BuildRequires : swig
Patch1: build.patch

%description
DH, EC, HMACs, message digests, symmetric ciphers (including AES); SSL
        functionality to implement clients and servers; HTTPS extensions to Python's
        httplib, urllib, and xmlrpclib; unforgeable HMAC'ing AuthCookies for web
        session management; FTP/TLS client and server; S/MIME; M2Crypto can also be
        used to provide SSL for Twisted. Smartcards supported through the Engine
        interface.

%package license
Summary: license components for the M2Crypto package.
Group: Default

%description license
license components for the M2Crypto package.


%package python
Summary: python components for the M2Crypto package.
Group: Default
Requires: M2Crypto-python3 = %{version}-%{release}
Provides: m2crypto-python

%description python
python components for the M2Crypto package.


%package python3
Summary: python3 components for the M2Crypto package.
Group: Default
Requires: python3-core

%description python3
python3 components for the M2Crypto package.


%prep
%setup -q -n M2Crypto-0.35.2
cd %{_builddir}/M2Crypto-0.35.2
%patch1 -p1

%build
## build_prepend content
rm SWIG/_m2crypto_wrap.c
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579209659
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/M2Crypto
cp %{_builddir}/M2Crypto-0.35.2/LICENCE %{buildroot}/usr/share/package-licenses/M2Crypto/6a8260c72527a57012ddf894d5e3357f25407375
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/M2Crypto/6a8260c72527a57012ddf894d5e3357f25407375

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
