#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE09FEF25D96484AC (mcepl@suse.cz)
#
Name     : M2Crypto
Version  : 0.30.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/41/50/7d85dc99b1c4f29eca83873d851ec29a8e484a66b31351e62e30be9db7d1/M2Crypto-0.30.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/41/50/7d85dc99b1c4f29eca83873d851ec29a8e484a66b31351e62e30be9db7d1/M2Crypto-0.30.1.tar.gz
Source99 : https://files.pythonhosted.org/packages/41/50/7d85dc99b1c4f29eca83873d851ec29a8e484a66b31351e62e30be9db7d1/M2Crypto-0.30.1.tar.gz.asc
Summary  : M2Crypto: A Python crypto and SSL toolkit
Group    : Development/Tools
License  : MIT MIT-Opengroup
Requires: M2Crypto-python3
Requires: M2Crypto-python
Requires: typing
BuildRequires : buildreq-distutils3
BuildRequires : openssl-dev
Patch1: build.patch
Patch2: rc4.patch

%description
DH, EC, HMACs, message digests, symmetric ciphers (including AES); SSL
        functionality to implement clients and servers; HTTPS extensions to Python's
        httplib, urllib, and xmlrpclib; unforgeable HMAC'ing AuthCookies for web
        session management; FTP/TLS client and server; S/MIME; M2Crypto can also be
        used to provide SSL for Twisted. Smartcards supported through the Engine
        interface.

%package doc
Summary: doc components for the M2Crypto package.
Group: Documentation

%description doc
doc components for the M2Crypto package.


%package python
Summary: python components for the M2Crypto package.
Group: Default
Requires: M2Crypto-python3
Provides: m2crypto-python

%description python
python components for the M2Crypto package.


%package python3
Summary: python3 components for the M2Crypto package.
Group: Default
Requires: python3-core

%description python3
python3 components for the M2Crypto package.


%prep
%setup -q -n M2Crypto-0.30.1
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536936555
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/M2Crypto
cp LICENCE %{buildroot}/usr/share/doc/M2Crypto/LICENCE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/M2Crypto/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
